# Site settings
title: 自由天空
description: > # this means to ignore newlines until "baseurl:"
  工作记录
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://0535.github.io # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Admin

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
github: '0535'

# avatar and Favicon
avatar: http://pic.yupoo.com/bztd/Gnsw55iB/54gX1.jpg
favicon: http://download.easyicon.net/ico/1200853/16/


# Build settings
# permalink: /:year/:month/:day/:title.html
# permalink: /:month-:day-:year/:title
# permalink: /:title.html
permalink: /:year-:month-:day
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

gems:
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-feed
 
